### ISSUE TITLE
SCPS-10118: Crash Bandicoot Racing (Japan)

### ISSUE THREAD

**Issue by FRDS** [HeatXD/duckstation-fightcade-savestates#425] opened 2023-05-27 09:37 UTC
### Hash
MD5: fd9fd3e036bab316b846bc056ec0de82

### Description
- Unlocks all characters, tracks, cups and difficulties.
- Cheats enabled, no need for memory card.
- Boots at title screen

### Savestate
[SCPS-10118.zip](https://github.com/HeatXD/duckstation-fightcade-savestates/files/11581446/SCPS-10118.zip)

**Comment by bigbangblitz** [comment] 2023-05-28 00:03
Closed for duplicate of issue https://github.com/HeatXD/duckstation-fightcade-savestates/issues/208

**Closed as completed by bigbangblitz** 2023-05-28 00:03 UTC
